sudo: required
services:
  - docker

before_install:
  - docker build -t ricardohan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ricardohan/docker-react npm run test -- --coverage
